// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";
import type { MembershipControl } from "./MembershipControl";
import type { Note } from "./Note";

/**
 * Details about a project that exists in a portal.
 * This holds all data as "option" as not all details
 * will be set by all portals. Also, using "option" allows
 * this struct to be used in "update" requests, as only
 * the fields that are set will be updated.
 *
 */
export type AwardDetails = { 
/**
 * The name of the project
 */
name: string | null, 
/**
 * The template used for the project
 */
template: string | null, 
/**
 * The key that may need to be provided to show that the
 * project is really allowed to access a particular type
 * of project (i.e. it may be very easy to guess an allowed
 * template name, but it would not be easy to guess the
 * associated key)
 */
key: string | null, 
/**
 * The description of the project
 */
description: string | null, 
/**
 * The email address(es) of the members of the project,
 * (keys) and their roles (values).
 */
members: { [key in string]?: string } | null, 
/**
 * Proposed start date of the project (ISO 8601 date string)
 */
start_date: string | null, 
/**
 * Proposed end date of the project (ISO 8601 date string)
 */
end_date: string | null, 
/**
 * The allocation of resource for this project (e.g. "1000 NHR")
 */
allocation: string | null, 
/**
 * A free-form breakdown of the allocation into named components.
 * Keys and values are arbitrary strings agreed between the local
 * and remote portals — OpenPortal does not interpret them.
 * e.g. {"project_storage": "5 TB", "gpu_hours": "500 GPUHR"}
 */
breakdown: { [key in string]?: string }, 
/**
 * Link back to the award record on the funding body's system
 */
award?: Link, 
/**
 * Link to the funding call from which the award was made
 */
call?: Link, 
/**
 * Link to the project page on the remote/awarding portal
 */
project_link?: Link, 
/**
 * Link to the page where more time / renewal can be requested
 */
renewal?: Link, 
/**
 * Notes attached to this award (append-only log of messages)
 */
notes: Array<Note>, 
/**
 * The earliest UTC time at which this award may be approved on the
 * receiving portal. Lets the awarder make corrections in the window
 * between creating the award and it being provisioned.
 */
earliest_approve?: string, 
/**
 * Controls whether the receiving portal may independently modify
 * membership or roles. When absent, behaviour is `Open`.
 */
membership_control?: MembershipControl, 
/**
 * The list of allowed domains for this project.
 * If this is None, then all domains are allowed.
 * If this is Some(vec![]), then no domains are allowed.
 * If this is Some(vec![...]), then only the domains that match
 * those in the list are allowed.
 */
allowed_domains: Array<string> | null, };
