// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Usage } from "./Usage";

export type DailyProjectUsageReport = { reports: { [key in string]?: Usage }, components: { [key in string]?: { [key in string]?: Usage } }, 
/**
 * Per-user job counts. Empty when reading data from older instances.
 */
user_job_counts: { [key in string]?: bigint }, 
/**
 * Per-user wait seconds. Empty when reading data from older instances.
 */
user_wait_seconds: { [key in string]?: bigint }, 
/**
 * Scalar total — equals sum of user_job_counts when populated, otherwise
 * carries the value from older instances that lack per-user maps.
 */
num_jobs: bigint, 
/**
 * Scalar total — equals sum of user_wait_seconds when populated.
 */
total_wait_seconds: bigint, is_complete: boolean, };
