// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quota } from "./Quota";

/**
 * An internal point-in-time snapshot of storage quota data for a single
 * project. Used to store historical entries inside `ProjectStorageReport`.
 * Not exposed through the public API — callers always receive
 * `ProjectStorageReport` even for individual days.
 */
export type DailyStorageReport = { project: string, generated_at: string, project_quotas: { [key in string]?: Quota }, user_quotas: { [key in string]?: { [key in string]?: Quota } }, };
