// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpiredJobEntry } from "./ExpiredJobEntry";
import type { FailedJobEntry } from "./FailedJobEntry";
import type { LogEntry } from "./LogEntry";
import type { RunningJobEntry } from "./RunningJobEntry";
import type { SlowJobEntry } from "./SlowJobEntry";

/**
 * Diagnostics report containing troubleshooting information
 */
export type DiagnosticsReport = { 
/**
 * Agent name
 */
agent_name: string, 
/**
 * When this report was generated
 */
generated_at: string, 
/**
 * Failed jobs (deduplicated, most recent 100)
 */
failed_jobs: Array<FailedJobEntry>, 
/**
 * Slowest successful jobs (top 100)
 */
slowest_jobs: Array<SlowJobEntry>, 
/**
 * Expired jobs (most recent 100, deduplicated)
 */
expired_jobs: Array<ExpiredJobEntry>, 
/**
 * Currently running jobs (deduplicated with count)
 */
running_jobs: Array<RunningJobEntry>, 
/**
 * System warnings and issues
 */
warnings: Array<string>, 
/**
 * Recent log messages (most recent first, up to 100)
 */
recent_logs: Array<LogEntry>, };
