// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entry for an expired job
 */
export type ExpiredJobEntry = { 
/**
 * Job destination
 */
destination: string, 
/**
 * Job instruction
 */
instruction: string, 
/**
 * When job was created
 */
created_at: string, 
/**
 * When job expired
 */
expired_at: string, 
/**
 * Number of times this job type expired
 */
count: number, };
