// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entry for a failed job
 */
export type FailedJobEntry = { 
/**
 * Job destination
 */
destination: string, 
/**
 * Job instruction
 */
instruction: string, 
/**
 * Error message
 */
error_message: string, 
/**
 * Number of times this failed
 */
count: number, 
/**
 * First occurrence
 */
first_seen: string, 
/**
 * Most recent occurrence
 */
last_seen: string, };
