// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from "./Type";

/**
 * Health information for an agent
 */
export type HealthInfo = { 
/**
 * Agent name
 */
name: string, 
/**
 * Agent type
 */
agent_type: Type, 
/**
 * Whether agent is connected
 */
connected: boolean, 
/**
 * Number of active jobs on this agent's boards
 */
active_jobs: number, 
/**
 * Number of pending jobs
 */
pending_jobs: number, 
/**
 * Number of running jobs
 */
running_jobs: number, 
/**
 * Number of completed jobs (on boards)
 */
completed_jobs: number, 
/**
 * Number of duplicate jobs
 */
duplicate_jobs: number, 
/**
 * Number of successfully completed jobs
 */
successful_jobs: number, 
/**
 * Number of jobs that expired
 */
expired_jobs: number, 
/**
 * Number of jobs that errored (not including expired)
 */
errored_jobs: number, 
/**
 * Number of jobs in-flight (passing through intermediate agents)
 */
inflight_jobs: number, 
/**
 * Number of jobs queued (waiting for connection)
 */
queued_jobs: number, 
/**
 * Number of active worker tasks processing messages
 */
worker_count: number, 
/**
 * Memory usage of this agent process in bytes
 */
memory_bytes: bigint, 
/**
 * CPU usage of this agent process (percentage, 0.0-100.0)
 */
cpu_percent: number, 
/**
 * Total system memory in bytes
 */
system_memory_total: bigint, 
/**
 * Number of CPU cores on the system
 */
system_cpus: number, 
/**
 * Minimum job execution time in milliseconds
 */
job_time_min_ms: number, 
/**
 * Maximum job execution time in milliseconds
 */
job_time_max_ms: number, 
/**
 * Mean job execution time in milliseconds
 */
job_time_mean_ms: number, 
/**
 * Median job execution time in milliseconds
 */
job_time_median_ms: number, 
/**
 * Number of jobs timed
 */
job_time_count: number, 
/**
 * All-time total number of successfully completed jobs (from diagnostics)
 */
total_completed: number, 
/**
 * All-time total number of failed jobs (from diagnostics)
 */
total_failed: number, 
/**
 * All-time total number of expired jobs (from diagnostics)
 */
total_expired: number, 
/**
 * All-time total number of slow jobs (from diagnostics)
 */
total_slow: number, 
/**
 * Time when agent started
 */
start_time: string, 
/**
 * Current time on agent
 */
current_time: string, 
/**
 * Uptime in seconds
 */
uptime_seconds: bigint, 
/**
 * Engine name (e.g., "templemeads")
 */
engine: string, 
/**
 * Engine version
 */
version: string, 
/**
 * Time when this health response was received/cached
 */
last_updated: string, 
/**
 * Nested health information from downstream peers
 */
peers: { [key in string]?: HealthInfo }, };
