// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export type Job = { id: string, created: number, changed: number, expires: number, version: number, command: string, state: Status, result: string | null, result_type: string | null, };
