// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Job statistics totals for all time
 */
export type JobStatistics = { 
/**
 * Total number of successfully completed jobs
 */
total_completed: number, 
/**
 * Total number of failed jobs
 */
total_failed: number, 
/**
 * Total number of expired jobs
 */
total_expired: number, 
/**
 * Total number of slow jobs (>1s duration)
 */
total_slow: number, };
