// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an external resource: an optional human-readable ID
 * and an optional URL. Used for award, call, project, and renewal links
 * inside AwardDetails.
 */
export type Link = { 
/**
 * Human-readable identifier, e.g. "EP/X000000/1" or "061-4738952-1"
 */
id: string | null, 
/**
 * URL pointing to the resource (must be a valid URL if provided)
 */
url: string | null, };
