// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single log message captured from the tracing framework
 */
export type LogEntry = { 
/**
 * When the message was logged
 */
timestamp: string, 
/**
 * Log level (ERROR, WARN, INFO, DEBUG, TRACE)
 */
level: string, 
/**
 * Module/target that produced the message
 */
target: string, 
/**
 * The log message text
 */
message: string, };
