// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls whether the receiving portal may independently modify the membership
 * or roles of a project.
 *
 * When this field is absent (`None` on `AwardDetails`) the behaviour is
 * identical to `Open` — the receiving portal manages membership freely.
 * Explicitly setting a value lets the sending portal declare a policy that
 * the receiving portal is expected to honour.
 */
export type MembershipControl = "open" | "members_only" | "roles_only" | "locked";
