// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A timestamped note attached to an award. Notes are append-only
 * messages, typically used by the awarding portal to communicate
 * with the project team.
 */
export type Note = { 
/**
 * When the note was created (UTC)
 */
timestamp: string, 
/**
 * Name of the person who created the note
 */
author: string, 
/**
 * Free-text content of the note
 */
text: string, };
