// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification statistics totals for all time
 */
export type NotificationStatistics = { 
/**
 * Total notifications received by this agent (inbound from the network)
 */
total_received: number, 
/**
 * Total notifications successfully sent (delivered to next hop or web portal)
 */
total_sent: number, 
/**
 * Total notifications that failed to deliver after all retries
 */
total_failed: number, };
