// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyStorageReport } from "./DailyStorageReport";
import type { Quota } from "./Quota";

/**
 * A report of the storage quotas and usage for a single project, including
 * per-user quotas. The top-level fields always hold the **most recent**
 * snapshot. Older point-in-time snapshots are stored in `daily_reports`,
 * keyed by calendar date (UTC), with at most one snapshot per date (the
 * newest seen for that date). The date of the top-level snapshot is never
 * duplicated in `daily_reports`.
 */
export type ProjectStorageReport = { 
/**
 * The project this report is for
 */
project: string, 
/**
 * When the top-level snapshot was generated
 */
generated_at: string, 
/**
 * Project-level quotas keyed by volume name (e.g. "home", "scratch")
 */
project_quotas: { [key in string]?: Quota }, 
/**
 * Per-user quotas: portal UserIdentifier → (volume → quota)
 */
user_quotas: { [key in string]?: { [key in string]?: Quota } }, 
/**
 * Mapping from portal UserIdentifier to local username
 */
users: { [key in string]?: string }, 
/**
 * Historical snapshots keyed by date (UTC). Each entry is the newest
 * snapshot seen for that day. The current top-level date is excluded.
 */
daily_reports: { [key in string]?: DailyStorageReport }, };
