// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyProjectUsageReport } from "./DailyProjectUsageReport";

export type ProjectUsageReport = { project: string, reports: { [key in string]?: DailyProjectUsageReport }, users: { [key in string]?: string }, };
