// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a storage quota with a limit and optional current usage
 */
export type Quota = { 
/**
 * Limit expressed as a human-readable size string (e.g. "100GB") or "unlimited"
 */
limit: string, 
/**
 * Current usage expressed as a human-readable size string (e.g. "2.5GB")
 */
usage: string | null, };
