// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entry for a currently running job
 */
export type RunningJobEntry = { 
/**
 * Job destination
 */
destination: string, 
/**
 * Job instruction
 */
instruction: string, 
/**
 * When the job started
 */
started_at: string, 
/**
 * Number of instances running
 */
count: number, 
/**
 * How long it's been running (seconds)
 */
running_for_seconds: bigint, };
