// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entry for a slow job
 */
export type SlowJobEntry = { 
/**
 * Job destination
 */
destination: string, 
/**
 * Job instruction
 */
instruction: string, 
/**
 * Duration in milliseconds
 */
duration_ms: number, 
/**
 * When it completed
 */
completed_at: string, };
