// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectStorageReport } from "./ProjectStorageReport";

/**
 * A portal-level storage report containing per-project storage reports for
 * all projects associated with a portal.
 */
export type StorageReport = { portal: string, reports: { [key in string]?: ProjectStorageReport }, };
