// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectUsageReport } from "./ProjectUsageReport";

export type UsageReport = { portal: string, reports: { [key in string]?: ProjectUsageReport }, };
