// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Usage } from "./Usage";

export type UserUsageReport = { user: string, usage: Usage, };
