// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a storage volume (e.g., "home", "scratch", "project")
 */
export type Volume = string;
